project:
  base-resource-dir: classpath:/

mybatis:
  configPath: META-INF/mybatis/mybatis.xml

dataSource:
  driverClassName: net.sf.log4jdbc.DriverSpy
  url: jdbc:log4jdbc:mysql://150.150.206.50:3306/sbc?zeroDateTimeBehavior=convertToNull
  username: root
  password: Posgen201%
  testOnBorrow: true
  validationQuery: SELECT 1

mail :
  host : smtp.gmail.com
  port : 587
  username : wykim@cloud4u.co.kr
  password : 755486sk
  encoding : UTF-8
  smtpAuth : true
  smtpStarttlsEnable : true

server:
  port: 8099
  error:
    whitelabel:
      enabled: false
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      charset: UTF-8
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB
  thymeleaf:
    prefix: ${project.base-resource-dir}templates/
    ## 개발모드
    cache: false
  resources:
    static-locations: ${project.base-resource-dir}static/
    ## 개발모드
    cache-period: 0